package cn.matrix.newpojo;

/**
 * @author Du
 * @version 1.0
 */
public enum PropertyList {
	NODE_GPS,WIRE_LENGTH, WIRE_CSAREA, WIRE_PHASE, WIRE_MATERIAL, WIRE_NAME, NODE_TYPE, NODE_PHASE, NODE_NAME, NODE_POWERR, NODE_T_JOINTRESISTANCE, NODE_TRANSFORMER_CAPACITY, NODE_TRANSFORMER_OUTVOLTAGE,NODE_TRANSFORMER_PHASE, NODE_LEVEL, NODE_USER_ID, NODE_BRANCHCOUNT, NODE_LOCATION
	,NODE_PIXEL,NODE_REMARK,USERNODE_LIST
}
